export { default as UI } from "./UI"
export { default as Header } from "./Header"
export { default as Gallery } from "./Gallery"
export { default as Footer } from "./Footer"
export { default as Search } from "./Search"
export { default as Loader } from "./Loader"